name: Swift

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build
      run: swift build -v
    - name: Run tests
      run: swift test -v
    - name: Run Todos tests
      run: xcodebuild clean test -workspace 'CombineBloc.xcworkspace' -scheme 'Todos' -sdk iphonesimulator -destination 'name=iPhone 8'
    - name: Run Login tests
      run: xcodebuild clean test -workspace 'CombineBloc.xcworkspace' -scheme 'Login' -sdk iphonesimulator -destination 'name=iPhone 8'
    - name: Run Counter tests
      run: xcodebuild clean test -workspace 'CombineBloc.xcworkspace' -scheme 'Counter' -sdk iphonesimulator -destination 'name=iPhone 8'
